sondages/models/sondage.py
from sondages.app import db, app, login_manager
from sqlalchemy.orm import with_polymorphic
from sqlalchemy.sql.expression import update
from flask.ext.login import UserMixin

#
# SONDAGE 
#

class Sondage(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(100))
  description = db.Column(db.String(1000))

  def __init__(self, name, description):
    super(Sondage, self).__init__()
    self.name = name
    self.description = description

  def __repr__(self):
    return "<Sondage (%d) %s>" % (self.id, self.name)

  def toDict(self):
    allQuestions = [x.toDict() for x in self.questions]
    return { 
              'id': self.id,
              'name': self.name,
              'description' : self.description,
              'questions' : allQuestions
            }

def getAllSondages():
  return Sondage.query.all()

def getSondage(id):
  return Sondage.query.filter(Sondage.id==id).first()

def getSondageId(name, description):
  return Sondage.query.filter(Sondage.name==name, Sondage.description==description).first().id

def addSondage(sondage):
  name = sondage['name']
  description = sondage['description']
  s = Sondage(name = name, description = description)
  db.session.add(s)
  db.session.commit()

def updateSondage(id, updatedSondage):
  session = db.session()
  sondage = session.query(Sondage).filter_by(id=id).first()
  sondage.name = updatedSondage['name']
  sondage.description = updatedSondage['description']
  session.commit()

def deleteSondage(sondage):
  for question in sondage.questions:
    reponses = Reponse.query.filter(Reponse.idQ == question.id).all()
    for reponse in reponses:
      db.session.delete(reponse)
  db.session().delete(sondage)
  db.session().commit()
 
#
# QUESTION 
#   

class Question(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  title = db.Column(db.String(120))
  sondage_id = db.Column(db.Integer, db.ForeignKey('sondage.id'))
  sondage = db.relationship("Sondage", backref=db.backref("questions", lazy="dynamic", cascade="all, delete-orphan"))
  type = db.Column(db.String(50))

  __mapper_args__ = {
      'polymorphic_identity': 'question',
      'polymorphic_on': type
  }

  def __repr__(self):
    return "<Question (%d) %s>" % (self.id, self.title)

  def toDict(self):
    return { 
              'id': self.id,
              'sondage_id': self.sondage_id,
              'title': self.title,
              'type': self.type
            }

class SimpleQuestion(Question):
  __tablename__ = 'simplequestion'

  id = db.Column(db.Integer, db.ForeignKey('question.id'), primary_key=True)
  firstAlternative = db.Column(db.String(500))
  secondAlternative = db.Column(db.String(500))
  firstChecked = db.Column(db.Boolean)

  __mapper_args__ = {
      'polymorphic_identity':'simplequestion'
  }

  def toDict(self):
    return { 
              'id': self.id,
              'sondage_id': self.sondage_id,
              'title': self.title, 
              'firstAlternative': self.firstAlternative, 
              'secondAlternative': self.secondAlternative,
              'firstChecked': self.firstChecked,
              'type': self.type
            }

def getAllQuestions():
  return db.session.query(Question).with_polymorphic(SimpleQuestion).all()

def addQuestion(question):
  id = question['sondage_id']
  title = question['title']
  firstAlternative = question['firstAlternative']
  secondAlternative = question['secondAlternative']
  firstChecked = question['firstChecked']
  if firstAlternative:
    q = SimpleQuestion(title=title, firstAlternative=firstAlternative, secondAlternative=secondAlternative, sondage_id=id, firstChecked=firstChecked)
  else:
    q = Question(title=title, sondage_id=id)
  db.session.add(q)
  db.session.commit()

def getQuestionsSlice(debut = 0, nombre = 10):
  return db.session.query(Question).with_polymorphic(SimpleQuestion).offset(debut).limit(nombre).all()

def getQuestion(id):
  return db.session.query(Question).with_polymorphic(SimpleQuestion).filter(Question.id==id).first()

def updateQuestion(id, sondage_id, title, firstAlternative="", secondAlternative="", firstChecked=False):
  session = db.session()
  question = session.query(Question).with_polymorphic(SimpleQuestion).filter_by(id=id).first()
  question.title = title
  question.sondage_id = sondage_id
  if firstAlternative:
    question.firstAlternative = firstAlternative
    question.secondAlternative = secondAlternative
    question.firstChecked = firstChecked
  session.commit()

def deleteQuestion(question):
  db.session().delete(question)
  db.session().commit()

#
# REPONSE 
#

class Reponse(db.Model):
  idQ = db.Column(db.Integer, primary_key=True)
  userPseudo = db.Column(db.String(100), primary_key=True)
  reponse = db.Column(db.String(1000))


  def toDict(self):
    return { 
              'question_id': self.idQ,
              'username': self.userPseudo,
              'answer' : self.reponse
            }
            
def getAllAnswers():
  return Reponse.query.all()

def getReponseForQuestion(idQ):
  return Reponse.query.filter(Reponse.idQ == idQ).all()

def getReponseForUser(pseudo):
  return Reponse.query.filter(Reponse.userPseudo == pseudo).all()

def getAnswer(idQ, pseudo):
  return Reponse.query.filter(Reponse.idQ == idQ, Reponse.userPseudo == pseudo).first()

def addAnswer(answer):
  idQ = answer['question_id']
  username = answer['username']
  answer = answer['answer']
  a = Reponse(idQ = idQ, userPseudo = username, reponse = answer)
  db.session.add(a)
  db.session.commit()

sondages/__init__.py
from .app import app, manager, db
import sondages.views
import sondages.commands

sondages/app.py
#! /usr/bin/env python3
from flask import Flask
app = Flask(__name__)
app.debug = True

from flask.ext.script import Manager
manager = Manager(app)

import os.path
def mkpath(p):
	return os.path.normpath(
		os.path.join(
			os.path.dirname(__file__),
			p))

from flask.ext.sqlalchemy import SQLAlchemy
app.config['SQLALCHEMY_DATABASE_URI'] = ('sqlite:///' + mkpath('../quest.db'))
db = SQLAlchemy(app)

from flask.ext.login import LoginManager
login_manager = LoginManager(app)

app.secret_key = '5S75L4nhFy9TF098tbfH'

app.config['SECRET_KEY'] = "24D99921-6556-45C3-AC7C-7821E5FBD238"

login_manager.login_view = "frontend.login"

from sondages.views import api
from sondages.views import frontend
app.register_blueprint(api.api)
app.register_blueprint(frontend.frontend)

sondages/views/api.py
from sondages.app import app
from flask import Blueprint, render_template, jsonify, request, abort, make_response, url_for, redirect
from sondages.models.sondage import *
from sondages.models.user import *
from flask.ext.login import logout_user, login_required, current_user

api = Blueprint('api', __name__, url_prefix='/api/v1.0')

@api.errorhandler(404)
def not_found(error):
  return make_response(jsonify({'error': 'Not found'}), 404)

@api.errorhandler(403)
def not_found(error):
  return make_response(jsonify({'error': 'Forbidden'}), 403)

@api.errorhandler(405)
def not_found(error):
  return make_response(jsonify({'error': 'Method not allowed'}), 405)

@api.errorhandler(400)
def not_found(error):
  return make_response(jsonify({'error': 'Bad Request'}), 400)

def make_public_question(question):
  new_question = {}
  for field in question:
      if field == 'id':
          new_question['uri'] = url_for('api.get_question', id=question['id'], _external=True)
      elif field == 'sondage_id':
          new_question['sondage_uri'] = url_for('api.get_sondage', id=question['sondage_id'], _external=True)
      else:
          new_question[field] = question[field]
  return new_question

def make_public_sondage(sondage):
  new_sondage = {}
  for field in sondage:
      if field == 'id':
          new_sondage['sondage_uri'] = url_for('api.get_sondage', id=sondage['id'], _external=True)
      elif field == 'questions':
          new_sondage['questions'] = [make_public_question(x) for x in sondage['questions']]
      else:
          new_sondage[field] = sondage[field]
  new_sondage['id'] = getSondageId(new_sondage['name'],new_sondage['description'])
  return new_sondage

@api.route("/questions", methods=['GET'])
def get_questions():
  return jsonify({ 'questions': [make_public_question(x.toDict()) for x in getAllQuestions()] })

@api.route("/sondages", methods=['GET'])
def get_sondages():
  return jsonify({ 'sondages': [make_public_sondage(x.toDict()) for x in getAllSondages()] })

@api.route("/questions", methods=['POST'])
def create_question():
  if not request.json or not 'title' in request.json or not 'sondage_id' in request.json:
    abort(400)
  question = {
    'sondage_id': request.json['sondage_id'],
    'title': request.json['title'],
    'firstAlternative': request.json.get('firstAlternative', ""),
    'secondAlternative': request.json.get('secondAlternative', ""),
    'firstChecked': request.json.get('firstChecked', False)
  }
  addQuestion(question)
  return jsonify({ 'question': make_public_question(question) }), 201

@api.route("/sondages", methods=['POST'])
def create_sondage():
  if not request.json or not 'name' or not 'description' in request.json:
    abort(400)
  sondage = {
    'name': request.json['name'],
    'description': request.json['description']
  }
  addSondage(sondage)
  return jsonify({ 'sondage': make_public_sondage(sondage) }), 201

@api.route("/questions/<int:id>", methods=['GET'])
def get_question(id):
  question = getQuestion(id)
  if not question:
    abort(404)
  return jsonify({'question': make_public_question(question.toDict())})

@api.route("/sondages/<int:id>", methods=['GET'])
def get_sondage(id):
  sondage = getSondage(id)
  if not sondage:
    abort(404)
  return jsonify({'sondage': make_public_sondage(sondage.toDict())})

@api.route("/sondages/<int:id>", methods=['PUT'])
def update_sondage(id):
  sondage = getSondage(id)
  if not sondage:
    abort(404)
  if not request.json or not 'name' in request.json or not 'description' in request.json:
    abort(400)
  updatedSondage = {
    'name': request.json['name'],
    'description': request.json['description']
  }
  updateSondage(id, updatedSondage)
  return jsonify({'sondage': updatedSondage})

@api.route("/questions/<int:id>", methods=['PUT'])
def update_question(id):
  question = getQuestion(id)
  if not question:
    abort(404)
  if not request.json:
    abort(400)
  if not 'sondage_id' in request.json or not 'title' in request.json:
    abort(400)
  if question.type == 'simplequestion':
    if not 'firstAlternative' in request.json:
      abort(400)
    if not 'secondAlternative' in request.json:
      abort(400)
    if not 'firstChecked' in request.json:
      abort(400)
  if 'sondage_id' in request.json and type(request.json['sondage_id']) is not int:
    abort(400)
  if 'firstChecked' in request.json and type(request.json['firstChecked']) is not bool:
    abort(400)
  if question.type == "simplequestion":
    updatedQuestion = {
      'sondage_id': request.json.get('sondage_id', question.sondage_id),
      'title': request.json.get('title', question.title),
      'firstAlternative': request.json.get('firstAlternative', question.firstAlternative),
      'secondAlternative': request.json.get('secondAlternative', question.secondAlternative),
      'firstChecked': request.json.get('firstChecked', question.firstChecked)
    }
    updateQuestion(id, updatedQuestion['sondage_id'], updatedQuestion['title'], updatedQuestion['firstAlternative'], updatedQuestion['secondAlternative'], updatedQuestion['firstChecked'])
  else:
    updatedQuestion = {
      'sondage_id': request.json.get('sondage_id', question.sondage_id),
      'title': request.json.get('title', question.title)
    }
    updateQuestion(id, updatedQuestion['sondage_id'], updatedQuestion['title'])
  return jsonify({'question': make_public_question(updatedQuestion)}), 200

@api.route("/questions/<int:id>", methods=['PATCH'])
def patch_question(id):
  question = getQuestion(id)
  if not question:
    abort(404)
  if not request.json:
    abort(400)
  if 'sondage_id' in request.json and type(request.json['sondage_id']) is not int:
    abort(400)
  if 'firstChecked' in request.json and type(request.json['firstChecked']) is not bool:
    abort(400)
  if question.type == "simplequestion":
    updatedQuestion = {
      'sondage_id': request.json.get('sondage_id', question.sondage_id),
      'title': request.json.get('title', question.title),
      'firstAlternative': request.json.get('firstAlternative', question.firstAlternative),
      'secondAlternative': request.json.get('secondAlternative', question.secondAlternative),
      'firstChecked': request.json.get('firstChecked', question.firstChecked)
    }
    updateQuestion(id, updatedQuestion['sondage_id'], updatedQuestion['title'], updatedQuestion['firstAlternative'], updatedQuestion['secondAlternative'], updatedQuestion['firstChecked'])
  else:
    updatedQuestion = {
      'sondage_id': request.json.get('sondage_id', question.sondage_id),
      'title': request.json.get('title', question.title)
    }
    updateQuestion(id, updatedQuestion['sondage_id'], updatedQuestion['title'])
  return jsonify({'question': make_public_question(updatedQuestion)}), 200

@api.route("/questions/<int:id>", methods=['DELETE'])
def delete_question(id):
  question = getQuestion(id)
  if not question:
    abort(404)
  deleteQuestion(question)
  return jsonify({'result': True}), 200

@api.route("/sondages/<int:id>", methods=['DELETE'])
def delete_sondage(id):
  sondage = getSondage(id)
  if not sondage:
    abort(404)
  deleteSondage(sondage)
  return jsonify({'result': True}), 200

@api.route("/users", methods=['POST'])
def create_user():
  username = request.json.get('username')
  password = request.json.get('password')
  if not username or not password:
    abort(400)
  if userExist(username):
    abort(400)
  newUser(username, password, 0)
  return jsonify({ 'username': user.pseudo }), 201, {'Location': url_for('api.get_user', id = user.id, _external = True)}

@api.route('/users/<string:username>', methods=['GET'])
def get_user(username):
  user = get_user_by_username(username)
  if not user:
      abort(404)
  return jsonify({'username': user.pseudo})

@api.route('/answers', methods=['POST'])
def create_answer():
  if not request.json or not 'question_id' in request.json or not 'username' in request.json or not 'answer' in request.json:
    abort(400)
  answer = getAnswer(request.json['question_id'], request.json['username'])
  if answer:
    abort(403)
  answer = {
    'question_id': request.json['question_id'],
    'username': request.json['username'],
    'answer': request.json['answer']
  }
  addAnswer(answer)
  return jsonify({ 'answer': answer }), 201

@api.route('/answers/<int:idQ>', methods=['GET'])
def get_answers_by_id(idQ):
  answer = getReponseForQuestion(idQ)
  if not answer:
    abort(404)
  return jsonify({'answers': [x.toDict() for x in answer]})

@api.route('/answers/<string:username>', methods=['GET'])
def get_answers_by_username(username):
  answer = getReponseForUser(username)
  if not answer:
    abort(404)
  return jsonify({'answers': [x.toDict() for x in answer]}) 

sondages/views/frontend.py
from sondages.app import app
from flask import Blueprint, render_template, jsonify, request, abort, make_response, url_for, redirect
from sondages.models.sondage import *
from sondages.models.user import *
from flask.ext.login import logout_user, login_required, current_user

frontend = Blueprint('frontend', __name__)

@frontend.route("/")
def home():
  if not current_user.is_authenticated():
    return render_template("home.html", title="Accueil")
  return render_template("sondages.html", title="Questions")

@frontend.route("/statistiques")
@login_required
def statistiques():
  return render_template("statistiques.html", title="Statistiques")

@frontend.route("/questions/")
@frontend.route("/questions/<int:debut>/")
@frontend.route("/questions/<int:debut>/<int:nombre>")
def questions(debut=0, nombre=10):
  return render_template(
    "flex.html",
    title="Questions",
    questions=getQuestionsSlice(debut, nombre))

@frontend.route("/login/", methods=("GET","POST",))
def login():
  f = LoginForm()
  if not f.is_submitted():
    f.next.data = request.args.get('next')
  elif f.validate_on_submit():
    user = f.get_authenticated_user()
    if user:
      login_user(user)
      next = f.next.data or url_for("frontend.home")
      return redirect(next)
    else :
      return render_template("login.html", 
                         form=f,
                         erreur=True)
  else :
    return render_template("login.html", 
                         form=f,
                         erreur=True)
  return render_template("login.html", 
                         form=f)

@frontend.route("/logout/")
@login_required
def logout():
  logout_user()
  return redirect(url_for("frontend.home"))

@frontend.route("/inscription/", methods=("GET","POST"))
def inscription():
  f = InscriptionForm()
  if not f.is_submitted():
    if current_user.is_authenticated():
      return redirect(url_for("frontend.home"))
  elif f.validate_on_submit():
    check = f.inscription()
    if check:
      return redirect(url_for("frontend.login"))
    else:
      return render_template("inscription.html",
                          title="Inscription",
                          form=f,
                          erreur=True)
  else :
    return render_template("inscription.html",
                          title="Inscription",
                          form=f,
                          erreur=True)
  return render_template("inscription.html",
                          title="Inscription",
                          form=f)

sondages/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>{% block title %}{{title}}{% endblock %}</title>
  {% block styles %}
  <link rel="stylesheet" href="{{ url_for('static', filename='normalize.css')}}">
  <link rel="stylesheet" href="{{ url_for('static', filename='font.css')}}">
  <link rel="stylesheet" href="{{ url_for('static', filename='primer.css')}}">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
  {% endblock %}
  {% block js %}
  <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
  {% endblock %}
</head>
<body>
  <header>
    <div class="container">
      <a href="{{ url_for('frontend.home') }}" class="header-title">IUT Sondage</a>
      {% if current_user.is_authenticated() %}
      <a href="{{ url_for('frontend.logout') }}" class="btn btn-reverse-header" role="button">Logout</a>
      {% else %}
      <div class="btn-group">
        <a href="{{ url_for('frontend.inscription') }}" class="btn btn-reverse-header" role="button">Sign in</a>
        <a href="{{ url_for('frontend.login') }}" class="btn btn-reverse-header" role="button">Login</a>
      </div>
      {% endif %}
      {% block navigation %}
      <nav>
        <a href="{{ url_for('frontend.home') }}">Sondage</a>
        <a href="{{ url_for('frontend.statistiques') }}">Statistiques</a>
      </nav>
      {% endblock %}
    </div>
  </header>
  {% block content %}{% endblock %}
  {% block footer %}
  <div class="container">
    <footer>
      <p>Copyright Sébastien Gédéon et Antoine Lassier 2015.<br>Créer dans le cadre d'un projet à l'IUT Informatique d'Orléans.</p>
    </footer>
  </div>
  {% endblock %}
</body>
  {% block script %}
  {% endblock %}
</html>

sondages/templates/flex.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8"/>
    <title>{% block title %}{{title}}{% endblock %}</title>
{% block styles %}
<link rel="stylesheet" 
      href="{{ url_for('static', filename='flex.css')}}"/>
{% endblock %}
{% block js %}
    <script src="{{ 
      url_for('static', filename='js/jquery.min.js') 
    }}">
    </script>
{% endblock %}
  </head>
  <body>
 <header>
 <h1>Administration des sondages</h1>
 </header>
 
 <div id='main'>
    
    <nav id="nav1">
      <h2>Questions</h2>
        {% block questions %}
          {% for question in questions %}
            <ul>
              <li>{{ question.title }}</li>
              <li>{{ question.sondage.name }}</li>
            </ul>
          {% endfor %}
        {% endblock %}
    </nav>
    
    <article> 
      <h2>Editeur de questions</h2>
      <span id="tool1">
        <img id="add" src="{{ url_for('static',  filename='img/new.png') }}" 
        alt="Nouvelle question"/>
      </span>
      {% block editor %}{%endblock %}
    </article>

    <nav id="nav2">
      <h2>Sondages</h2>
      <span id="tool2">
        <img id="save" src="{{ url_for('static', filename='img/save.png') }}" 
        alt="Enregistrer le sondage"/>
      </span>
      {% block surveys %} {% endblock %}
    </nav>
 
 </div>
 <footer>
 <h4>©Département Informatique ⚛ IUT d'Orléans</h4>
 </footer>

  </body>
</html>

sondages/templates/home.html
{% extends "base.html" %}

{% block content %}
  <div class="join">
    <div class="container">
      <h1>IUT Sondage</h1>
      <p>Répondez à des sondages et consultez vos statistiques.</p>
      <a href="{{ url_for('frontend.inscription') }}" role="button" class="btn btn-reverse">S'inscrire</a>
    </div>
  </div>
  <div class="container about">
    <div class="columns">
      <div class="one-third column">
        <h2>Des sondages</h2>
        <p>IUT Sondage est un site web créer spécialement pour que vous puissiez répondre a de multiples sondages en toute simplicité.</p>
      </div>
      <div class="one-third column">
        <h2>Des statistiques</h2>
        <p>Depuis l'onglet statistique vous pouvez consulter, de façon visuelle, vos statistiques pour chaque sondages.</p>
      </div>
      <div class="one-third column">
        <h2>API REST <span class="state state-closed">beta</span></h2>
        <p>Vous êtes développeur ? Notre site web proprose une API REST totalement fonctionnelle pour vous permettre de créer vos propres applications en utilisant nos services.</p>
      </div>
    </div>
  </div>
{% endblock %}

sondages/templates/inscription.html
{% extends "base.html" %}

{% block content %}
  <div class="join">
    <div class="container">
      <h1>S'inscrire</h1>
      <p>Veuillez remplir les champs ci-dessous</p>
      {% if erreur %}
        <div class="flash flash-logwarn">
          Erreur lors de l'inscription.
        </div>
      {% endif %}
      <form method="POST" class="auth-form" action="{{ url_for('frontend.inscription') }}">
      {{ form.hidden_tag() }}
        <label for="pseudo">{{ form.pseudo.label.text }}</label>
      {{ form.pseudo(class_="form-control", placeholder="pseudo", id="pseudo") }}
        <label for="mdp">{{ form.mdp.label.text }}</label>
      {{ form.mdp(class_="form-control", placeholder="mot de passe", id="mdp") }}
        <br>
        <button type="submit" class="btn btn-reverse">Valider</button>
      </form>
    </div>
  </div>
  <div class="container about">
    <p>Une fois votre incription terminée, vous pourrez accéder au sondages et commencer à répondre au questions.</p>
  </div>
{% endblock %}

sondages/templates/login.html
{% extends "base.html" %}

{% block content %}
  <div class="join">
    <div class="container">
      <h1>Se connecter</h1>
      <p>Veuillez remplir les champs ci-dessous</p>
      {% if erreur %}
        <div class="flash flash-logwarn">
          Erreur lors de la connexion.
        </div>
      {% endif %}
      {% if not current_user.is_authenticated() %}
        <form method="POST" class="auth-form" action="{{ url_for('frontend.login') }}">
          {{ form.hidden_tag() }}
          <label for="pseudo">{{ form.pseudo.label.text }}</label>
          {{ form.pseudo(class_="form-control", placeholder="pseudo", id="pseudo") }}
          <label for="mdp">{{ form.mdp.label.text }}</label>
          {{ form.mdp(class_="form-control", placeholder="mot de passe", id="mdp")  }}
          <br>
          <button type="submit" class="btn btn-reverse">Se connecter</button>
        </form>
      {% else %}
        <p>Vous êtes déjà connecté, {{ current_user.pseudo }}</p>
      {% endif %}
    </div>
  </div>
  <div class="container about">
    <p>Pas encore incrit ? vous pouvez vous inscrire <a href="{{ url_for('frontend.inscription') }}">ici</a>.</p>
  </div>
{% endblock %}

sondages/templates/questions-ajax.html
{% extends "flex.html" %}
{% block js %}
{{ super() }}

<script type="text/javascript">
    
$(function() {




  $("#button").click(function () {
    $.ajax({
      url: "{{ url_for('api.get_questions' ) }}",
      type: "GET",
      dataType: "json",
      success: function (data) {
          $("#questions").append($('<ul>'));
          for (var i = 0; i < data.questions.length; i++) {
            $("#questions ul")
            .append($('<li>')
              .append($("<a>")
                .attr({'href':""+data.questions[i].uri,
                  class:"question-link"})
                .text(data.questions[i].title)));
          }
      },
      error: function (req, status, err) {
        $('#questions').html("<b>Impossible de récupérer les questions ! </b>");
      }
    });
  });
  $("#questions").on('click', '.question-link', function(event) {
   event.preventDefault();
   $.ajax({
     url: $(this).attr('href'),
     type: "GET",
     dataType: "json",
     success: function (data) {
        $("#question-editor").append($('<form>'));
        for(attr in data.question){
          $("#currentQuestion form input[id="+attr+"]").val(data.question[attr]);
          if(attr == "firstChecked"){
            $("#currentQuestion form input[id="+attr+"]").prop("checked" , data.question[attr]);
          }
        }
        $("#currentQuestion form input[id=sendButton]").val("Editer");
     },
     error: function (req, status, err) {
       $('#questions').html("<b>Impossible de récupérer les questions ! </b>");
     }
   });
  });

  $("#tool1 #add").on("click", function() {
    $("#currentQuestion form input").each(function(index, el) {
      $(this).val("");
      if($(this).attr("id") == "sondage_id"){
        $(this).prop("value", 1);
      }
      if($(this).attr('type') == "checkbox"){
        $(this).prop("checked", false);
      }
    });
    $("#currentQuestion form input[id=sendButton]").val("Creer");
  });

  $("#sendButton").on('click', function(event) {
    event.preventDefault();
    var q = new SimpleQuestion($("#title").val(), $("#firstAlternative").val(), $("#secondAlternative").val(), Boolean($("#firstChecked").val()), parseInt($("#sondage_id").val()) );

    if($(this).val() == 'Editer'){
      $.ajax({
        url: $("#uri").val(),
        type: "PUT",
        contentType: 'application/json',
        dataType: "json",
        data: JSON.stringify(q),
        success: function (data) {
          console.log(data);
        },
        error: function (req, status, err) {
          $('#questions').html("<b>Impossible d'editer ! </b>");
        }
      });

    }else if($(this).val() =='Creer'){
      $.ajax({
              url: "{{ url_for('create_question' ) }}",
              type: "POST",
              contentType: 'application/json',
              dataType: "json",
              data: JSON.stringify(q),
              success: function (data) {
                console.log(data);
              },
              error: function (req, status, err) {
                $('#questions').html("<b>Impossible d'editer ! </b>");
              }
            });
    }
  });
  
});

function SimpleQuestion(title, firstAlternative, secondAlternative, firstChecked, sondage_id){
  this.type = "simplequestion";
  this.title = title;
  this.firstAlternative = firstAlternative;
  this.secondAlternative = secondAlternative;
  this.firstChecked = firstChecked;
  this.sondage_id = sondage_id;
}


</script>

{% endblock %}
{% block questions %}

  <input id="button" type="button" value="Recuperer les questions" />
  <div id="questions"></div>

{% endblock %}

{% block editor %}
<div id="currentQuestion">
  <form>
    <input type="text" id="title" ><br>
    <input type="text" id="firstAlternative" ><br>
    <input type="text" id="secondAlternative" ><br>
    <input type="checkbox" id="firstChecked" ><br>
    <input type="hidden" id="uri" value="" >
    <input type="hidden" id="sondage_id" value="1" >
    <input type="submit" id="sendButton" value="Ajouter">
  </form>
</div>
{% endblock %}
{% block surveys %}
  <div id="sondages">
    
  </div>
{% endblock %}